package com.example.valorant.jogador;

public record JogadorResponseDTO(
    Long id, 
    String username, 
    String tag, 
    String url, 
    double dpR, 
    double kdr, 
    double headshot, 
    double win, 
    double wins, 
    double kast, 
    double dddeltaR, 
    double kills, 
    double deaths, 
    double assists, 
    double acs, 
    double kadRatio, 
    double killsPerRound, 
    double clutch1v1s, 
    double flawlessRounds,
    double currentRating, 
    double peakRating, 
    double playtime, 
    double matches, 
    double level, 
    double losses,
    String topAgent1, 
    String topAgent2, 
    String topAgent3, 
    double topHoursAgent1, 
    double topHoursAgent2, 
    double topHoursAgent3, 
    double topMatchesAgent1, 
    double topMatchesAgent2, 
    double topMatchesAgent3, 
    double topWinAgent1, 
    double topWinAgent2, 
    double topWinAgent3, 
    double topKDAgent1, 
    double topKDAgent2, 
    double topKDAgent3, 
    String topWeapon1, 
    double topWeaponHeadshot1,
    double topWeaponBodyshot1,
    double topWeaponLegshot1,
    double topWeaponKills1,
    String topWeapon2, 
    double topWeaponHeadshot2,
    double topWeaponBodyshot2,
    double topWeaponLegshot2, 
    double topWeaponKills2,
    String topWeapon3, 
    double topWeaponHeadshot3,
    double topWeaponBodyshot3,
    double topWeaponLegshot3,
    double topWeaponKills3,
    String topMap1,
    double topMapWinrate1,
    double topMapWins1,
    double topMapLosses1,
    String topMap2,
    double topMapWinrate2,
    double topMapWins2,
    double topMapLosses2,
    String topMap3,
    double topMapWinrate3,
    double topMapWins3,
    double topMapLosses3,
    String topMap4,
    double topMapWinrate4,
    double topMapWins4,
    double topMapLosses4,
    String topMap5,
    double topMapWinrate5,
    double topMapWins5,
    double topMapLosses5,
    String topMap6,
    double topMapWinrate6,
    double topMapWins6,
    double topMapLosses6,
    String topMap7,
    double topMapWinrate7,
    double topMapWins7,
    double topMapLosses7,
    String topMap8,
    double topMapWinrate8,
    double topMapWins8,
    double topMapLosses8,
    String topMap9,
    double topMapWinrate9,
    double topMapWins9,
    double topMapLosses9,
    String topMap10,
    double topMapWinrate10,
    double topMapWins10,
    double topMapLosses10,
    double views
) {
    public JogadorResponseDTO(Jogador jogador) {
        this(
            jogador.getId(), 
            jogador.getUsername(), 
            jogador.getTag(), 
            jogador.getUrl(), 
            jogador.getDpR(), 
            jogador.getKdr(), 
            jogador.getHeadshot(), 
            jogador.getWin(), 
            jogador.getWins(), 
            jogador.getKast(), 
            jogador.getDddeltaR(), 
            jogador.getKills(), 
            jogador.getDeaths(), 
            jogador.getAssists(), 
            jogador.getAcs(), 
            jogador.getKadRatio(), 
            jogador.getKillsPerRound(), 
            jogador.getClutch1v1s(), 
            jogador.getFlawlessRounds(), 
            jogador.getCurrentRating(), 
            jogador.getPeakRating(), 
            jogador.getPlaytime(), 
            jogador.getMatches(), 
            jogador.getLevel(), 
            jogador.getLosses(), 
            jogador.getTopAgent1(), 
            jogador.getTopAgent2(), 
            jogador.getTopAgent3(), 
            jogador.getTopHoursAgent1(), 
            jogador.getTopHoursAgent2(), 
            jogador.getTopHoursAgent3(), 
            jogador.getTopMatchesAgent1(), 
            jogador.getTopMatchesAgent2(), 
            jogador.getTopMatchesAgent3(), 
            jogador.getTopWinAgent1(), 
            jogador.getTopWinAgent2(), 
            jogador.getTopWinAgent3(), 
            jogador.getTopKDAgent1(), 
            jogador.getTopKDAgent2(), 
            jogador.getTopKDAgent3(), 
            jogador.getTopWeapon1(), 
            jogador.getTopWeaponHeadshot1(), 
            jogador.getTopWeaponBodyshot1(),
            jogador.getTopWeaponLegshot1(),
            jogador.getTopWeaponKills1(),
            jogador.getTopWeapon2(), 
            jogador.getTopWeaponHeadshot2(), 
            jogador.getTopWeaponBodyshot2(),
            jogador.getTopWeaponLegshot2(),
            jogador.getTopWeaponKills2(),
            jogador.getTopWeapon3(), 
            jogador.getTopWeaponHeadshot3(),
            jogador.getTopWeaponBodyshot3(),
            jogador.getTopWeaponLegshot3(),
            jogador.getTopWeaponKills3(),
            jogador.getTopMap1(),
            jogador.getTopMapWinrate1(),
            jogador.getTopMapWins1(),
            jogador.getTopMapLosses1(),
            jogador.getTopMap2(),
            jogador.getTopMapWinrate2(),
            jogador.getTopMapWins2(),
            jogador.getTopMapLosses2(),
            jogador.getTopMap3(),
            jogador.getTopMapWinrate3(),
            jogador.getTopMapWins3(),
            jogador.getTopMapLosses3(),
            jogador.getTopMap4(),
            jogador.getTopMapWinrate4(),
            jogador.getTopMapWins4(),
            jogador.getTopMapLosses4(),
            jogador.getTopMap5(),
            jogador.getTopMapWinrate5(),
            jogador.getTopMapWins5(),
            jogador.getTopMapLosses5(),
            jogador.getTopMap6(),
            jogador.getTopMapWinrate6(),
            jogador.getTopMapWins6(),
            jogador.getTopMapLosses6(),
            jogador.getTopMap7(),
            jogador.getTopMapWinrate7(),
            jogador.getTopMapWins7(),
            jogador.getTopMapLosses7(),
            jogador.getTopMap8(),
            jogador.getTopMapWinrate8(),
            jogador.getTopMapWins8(),
            jogador.getTopMapLosses8(),
            jogador.getTopMap9(),
            jogador.getTopMapWinrate9(),
            jogador.getTopMapWins9(),
            jogador.getTopMapLosses9(),
            jogador.getTopMap10(),
            jogador.getTopMapWinrate10(),
            jogador.getTopMapWins10(),
            jogador.getTopMapLosses10(),
            jogador.getViews()
        );
    }
}