package com.example.valorant.jogador;

public record JogadorResponseDTO(
    Long id, 
    String username, 
    String tag, 
    String url, 
    String dpR, 
    String kdr, 
    String headshot, 
    String win, 
    double wins, 
    String kast, 
    String dddeltaR, 
    double kills, 
    double deaths, 
    double assists, 
    String acs, 
    String kadRatio, 
    String killsPerRound, 
    double clutch1v1s, 
    double flawlessRounds,
    String currentRating, 
    String peakRating, 
    double playtime, 
    double matches, 
    String level, 
    double losses,
    String topAgent1, 
    String topAgent2, 
    String topAgent3, 
    String topHoursAgent1, 
    String topHoursAgent2, 
    String topHoursAgent3, 
    String topMatchesAgent1, 
    String topMatchesAgent2, 
    String topMatchesAgent3, 
    String topWinAgent1, 
    String topWinAgent2, 
    String topWinAgent3, 
    String topKDAgent1, 
    String topKDAgent2, 
    String topKDAgent3, 
    String topWeapon1, 
    String topWeaponHeadshot1, 
    String topWeapon2, 
    String topWeaponHeadshot2, 
    String topWeapon3, 
    String topWeaponHeadshot3,
    String topMap1,
    String topMapWinrate1,
    String topMapWins1,
    String topMapLosses1,
    String topMap2,
    String topMapWinrate2,
    String topMapWins2,
    String topMapLosses2,
    String topMap3,
    String topMapWinrate3,
    String topMapWins3,
    String topMapLosses3,
    String topMap4,
    String topMapWinrate4,
    String topMapWins4,
    String topMapLosses4,
    String topMap5,
    String topMapWinrate5,
    String topMapWins5,
    String topMapLosses5,
    String views
) {
    public JogadorResponseDTO(Jogador jogador) {
        this(
            jogador.getId(), 
            jogador.getUsername(), 
            jogador.getTag(), 
            jogador.getUrl(), 
            jogador.getDpR(), 
            jogador.getKdr(), 
            jogador.getHeadshot(), 
            jogador.getWin(), 
            jogador.getWins(), 
            jogador.getKast(), 
            jogador.getDddeltaR(), 
            jogador.getKills(), 
            jogador.getDeaths(), 
            jogador.getAssists(), 
            jogador.getAcs(), 
            jogador.getKadRatio(), 
            jogador.getKillsPerRound(), 
            jogador.getClutch1v1s(), 
            jogador.getFlawlessRounds(), 
            jogador.getCurrentRating(), 
            jogador.getPeakRating(), 
            jogador.getPlaytime(), 
            jogador.getMatches(), 
            jogador.getLevel(), 
            jogador.getLosses(), 
            jogador.getTopAgent1(), 
            jogador.getTopAgent2(), 
            jogador.getTopAgent3(), 
            jogador.getTopHoursAgent1(), 
            jogador.getTopHoursAgent2(), 
            jogador.getTopHoursAgent3(), 
            jogador.getTopMatchesAgent1(), 
            jogador.getTopMatchesAgent2(), 
            jogador.getTopMatchesAgent3(), 
            jogador.getTopWinAgent1(), 
            jogador.getTopWinAgent2(), 
            jogador.getTopWinAgent3(), 
            jogador.getTopKDAgent1(), 
            jogador.getTopKDAgent2(), 
            jogador.getTopKDAgent3(), 
            jogador.getTopWeapon1(), 
            jogador.getTopWeaponHeadshot1(), 
            jogador.getTopWeapon2(), 
            jogador.getTopWeaponHeadshot2(), 
            jogador.getTopWeapon3(), 
            jogador.getTopWeaponHeadshot3(),
            jogador.getTopMap1(),
            jogador.getTopMapWinrate1(),
            jogador.getTopMapWins1(),
            jogador.getTopMapLosses1(),
            jogador.getTopMap2(),
            jogador.getTopMapWinrate2(),
            jogador.getTopMapWins2(),
            jogador.getTopMapLosses2(),
            jogador.getTopMap3(),
            jogador.getTopMapWinrate3(),
            jogador.getTopMapWins3(),
            jogador.getTopMapLosses3(),
            jogador.getTopMap4(),
            jogador.getTopMapWinrate4(),
            jogador.getTopMapWins4(),
            jogador.getTopMapLosses4(),
            jogador.getTopMap5(),
            jogador.getTopMapWinrate5(),
            jogador.getTopMapWins5(),
            jogador.getTopMapLosses5(),
            jogador.getViews()
        );
    }
}